Add user Auth / CRUD operations - WIP
ubclaunchpad/when3meet pull request #68
Opened 2021-02-05 05:46 UTC by jmengo

## Overview ⚙️

> Provide a brief description of what this PR is for.
Some client operations for Users such as login.

## Change Summary

> Provide a bullet-point summary of the changes that you made and why you made that change. For very small PRs you can skip this.
- User login (firebase auth) -> Also creates a user record in the realtime database
- User logout (firebase auth)
- Delete account (firebase auth)
- Update user record in db

NOTE: There are some lines i left in so you guys can test this stuff yourself easily by going to the `/register` route and clicking around with the buttons. We don't have error handling on the front end yet AFAIK so errors are just logged to console. This is still a work in progress since we need to implement calendar and we should revisit our data model.

## Screenshots

> When relevant, provide a screenshot of the changes.

## Related Issues ⚠️

> Put any issue that this PR addresses here. Make sure you use a [closing keyword](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so GitHub knows to link the issue(s).

2021-02-05 06:00 UTC, michelleykim approved these changes

2021-02-05 22:59 UTC, narendrasss requested changes
Thanks for getting this started! Just a small nitpick, everything else looks good.

2021-02-05 22:59 UTC, narendrasss commented on src/user/components/SignupPage.vue
> +      client.deleteUser();
You can remove the `async` from these methods and just return the stuff from the client :)

e.g.

```js
signUp() {
  return client.createUser(this.email, this.password)
}
```

2021-02-11 05:27 UTC, narendrasss approved these changes

2021-02-11 05:28 UTC, merged